# If hostname or wlan_interface not specified,
# the program will automatically retrieve them.
# Otherwise, the specified one used.
probeNode:
  hostname: ""
  wlanInterface: ""
influxdb:
  host: "http://127.0.0.1"
  port: "8086"
  username: "root"
  password: "root"
  database: "wifimonitor"
  measurement: "SIGNALSTR"
  retentionPolicy: "onehour"