wireless:
  SSID: asdsadfdsf
  Passphrase: asdfdsfasfasfsdf
probeNode:
  uniqueID: asdf
  alias: RasPi
  wlanInterface: ''
  location: Ruang Test 1
influxdb:
  host: http://192.168.41.209
  port: '8086'
  username: root
  password: root
  database: bpg-wifimon-test
  measurement: SIGNALSTR
  retentionPolicy: onehour
